GET http://localhost:8080/student/read/

###
GET http://localhost:8080/student/read/63267afd51cc60321f1fd9ac

###
GET http://localhost:8080/student/search?input=201

###
POST http://localhost:8080/student/add
Content-Type: application/json

{
    "nim": "asd",
    "nama": "123",
    "gender": "Pria",
    "telp": "abc",
    "jurusan": "aaa"
}

### 
PATCH http://localhost:8080/student/update/6320ff9644d2834a4695241f
Content-Type: application/json

{
    "nim": "2018802312",
    "nama": "Jeremy Santoso",
    "gender": "Pria",
    "telp": "08234567891",
    "jurusan": "Teknik Komputer Jaringan"
}

###
DELETE http://localhost:8080/student/delete/632aa9b5bc2b4ff363a34e71
